# Generated by Django 5.1.3 on 2024-11-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_remove_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(default="", upload_to="posts"),
            preserve_default=False,
        ),
    ]
